//
// Created by andreas on 15.09.24.
//

#include "./../find_longest_substring_with_even_vowl_count.h"
#include "gtest/gtest.h"

TEST(TestFindLongestSubStringWithEvenVowlCount, simple1)
{
    std::string input{"eleetminicoworoep"};
    constexpr int expected_result{13};
    EXPECT_EQ(expected_result, find_longest_valid_substring(input));
}

TEST(TestFindLongestSubStringWithEvenVowlCount, simple2)
{
    std::string input{"leetcodeisgreat"};
    constexpr int expected_result{5};
    EXPECT_EQ(expected_result, find_longest_valid_substring(input));
}

TEST(TestFindLongestSubStringWithEvenVowlCount, simple3)
{
    std::string input{"sdfghhhhhjkll"};
    constexpr int expected_result{13};
    EXPECT_EQ(expected_result, find_longest_valid_substring(input));
}

TEST(TestFindLongestSubStringWithEvenVowlCount, simple4)
{
    std::string input{"abcdefg"};
    constexpr int expected_result{3};
    EXPECT_EQ(expected_result, find_longest_valid_substring(input));
}

TEST(TestFindLongestSubStringWithEvenVowlCount, complex1)
{
    std::string input{"lcwbgnkxnooovtxtuuolbgvieqyxdzyngkdaxuhgwzmgjjvylhavhtijfzvwdalxewsympoyvdhtlbchfgnexmmslcbrozsljwlxzkladmjibvyqpibpkwnxosrqhfqbmigkgxdtfnnsitxecihwisfonaejqeenboqxpqxbmdwzxjnodurnznaitbjikqaerbgkxdfjxnqyecqpqcnluezomtkvjprcqeaucgttwlpqeyfwenybcluxwzjvixlljnmpolktwnezewpiuwinsptbjqzplpeoeuwpehkycvrsslfznunjihtauplcipxmobnipqekegxmddzkepuqzoqepebgwmkuxipjbncgaskmzjhjnlokvxidvlbjgxsdtxiaikdmojrilepbdmokaouhekegpfjlhuywvgtbtozivvooplnnchlbkdvmrwwpkegczippokorcptixrudwszencxemdnxrgearvtddcukdvsrulnvmcnuojxynomtrteotpmdkiueivbdyfxvbakkbfnotanrsmdvmbaehqpumkejtessereyeshxgagprozlpunqanhwmitayqkdzqyhnieqosyrlidxxxcwlmolnvqopmrabpkyhdalcwfwpdheoxcfuiypwlfhbjuorrotjhajpeggfjcifmuzyszjxyfomvczltlhazrtfotejmekkiaegiguabubojhqyudxctegfanffokbotqlwjsertqbhdophqkdvjeiunidaalqfbkfbbaihaxjpxxtupkscgflwxczlelgomoltschhdhcxjqlcdstlhrjyujzdfwngoeygcncmeshjitqxspmddvlopvmgskeuikugtbvmikzdueglpuksbbwoeopqygziitejdkhkkgydngnyeqrcmamemltyqmtexvcyvqhygppmywkiraqyqwxxiamxqmeftidndwpmbpcschkmtvvklwvyihneyhvmtxbhgseskfdygnbqkrywllvwnhlymchoelulcoqznmyicooveiwwazqlnhlwozkoqyaezwyhzwdhilhsfollwbwvfmrllvrsnjqiocbdrixjzgnrszghicnmvqjjtpcnhwgpdqlsyrcbckhocgboecvpczbepewpnpjatirudtcurrtlbhrvreaymbekvmrzctyojkgnpcmyizauvudjxhssmamcuschcnqorjqybepptlerdgirzapuvsoeekmoitoszlwmyvtscagrhhtvlnrydcayhukhxgqfrcqfbjuiswvklnlygatspefmafailygnvgzhnvsgnsmbfsaugdbjermtlfsyvffqepucofzyjilohswbxhugzzihzxwnxwiwhlzpnzgoqvqzkbhhrendrcynnqmtodzgbmgrwgnqxqwtqtpyludmuvyjqzlkfnvzrhgchcivnxhpuibmlmongbjheekvvxrvjtsonvjlxkihomxkbsygzyvdvuehlewqoymiankekcgmgmtqrcvuogdezmdmyqsxzyhoyprcfyalbsoeypmgxgtbkgpixfrpqxqnbegajnwcfuamjqejefjqhzzvjzotgqgwbgtmklvmybvmcfpeljfbwpollltqxrgyrehnzvchijrokuoapwpeanmfjrwmgsvmzxwahupklojcbqkfeblphtuwbbapooynhmfdhjjhadgnvjpyizjduoeikzjsrkbjgioqxqhyakodcnlibewwuqjlzkmfybokfthpftnrmdjyctofsnpuexcarwrpstrehbrzjnzvsoislrkqlsbfnhpulvixxyhctijqybjppwfcvsqrgbssqkjcrthsufevxnutkuwgtyovfaygbacmzlngfanbhbmdllrtemqudxkpuaohmrcntsmalqjhmpmlbbntnsfwekgepnkyyalllxczymewubebxjikbceehkgyfognlejzsfoasfxudbxenvjqygbctqyqrwnxiwprooustcskdjhybhdgfuymymueshrugpwsuevxuydmolvatzpupybhtjfqtpcxkciwzqjverubkceqwefvyatrabcyrlpbvquvrcoosvailoclcffysasmgsvhepdlqvptdxtrvfqjdjctdskrosxsjojyqozzrosejsicvjbsmwepsuyxwkvidsjnhhmrscmveibviyhkcimdehpkonycqsobngmssvyittyeembauboalqokzfwvgxotgvgmkywoiifjvcyttrcqtpssrhdpdoqrfdwukqwzmshqdzohdycpisqjaktzvzmhneqsocpinxzrsrcwdmdimbcrlcmvppxvuufmbimvmmoawvhrecpmgdywwogmumnaziaybpxneytfxgqmjcrbnweofjbujsjbtqkjbpcfxuyvytmwupiozanbjyblgkfhecbdejkpsstpamsrmhxqerydnrmhratsrknzmruvgenfdsdxjflppyqfsiuwhicwqkhuztrhiyfuebolethjxbnopxbfrmzvvpuxkjiflvqxxlcynhwldlhwclvrvvvjbslqamvdaasfodglcqemfotdqiwpzflveduecumffhzjdbtgatwgazuowgtmjekltmdzttgkanoxgfaqiohzccgtxehzhwrlqqasqgobdfnevzpqhhblfzrvfnrhilyyuztrgjshdrbkjrfxenkrjtayurhakpbgmdowuzmprrgyyodvugyyufuitwiaczvvmazgqkiusgypreobmqmmbubjlhxgorppbyrgdkwjnxzhwxfisivrsldvwlnqnophdfqtotobdcmmyiguvpsvvltmrqzdsahpmiticfmdzb"};
    constexpr int expected_result{2870};
    EXPECT_EQ(expected_result, find_longest_valid_substring(input));
}
