//
// Created by andreas on 26.07.24.
//

#ifndef DATA_STRUCTURES_TEST_CITY_WITH_SMALLEST_NUMBER_OF_NEIGHBORS_IN_DISTANCE_H
#define DATA_STRUCTURES_TEST_CITY_WITH_SMALLEST_NUMBER_OF_NEIGHBORS_IN_DISTANCE_H

#include "graphs/city_with_smallest_number_of_neighbors_in_distance.h"

#endif //DATA_STRUCTURES_TEST_CITY_WITH_SMALLEST_NUMBER_OF_NEIGHBORS_IN_DISTANCE_H
