//
// Created by andreas on 14.04.23.
//
#include "gtest/gtest.h"
#include "length_of_longest_palindromic_subsequence.h"

TEST(LengthOfLongestPalindromicSubsequence, short1)
{
	std::string input{"bbac"};
	int expected_result{2};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence(input));
}

TEST(LengthOfLongestPalindromicSubsequence, short2)
{
	std::string input{"abbac"};
	int expected_result{4};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence(input));
}

TEST(LengthOfLongestPalindromicSubsequence, long1)
{
	std::string input
		{"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"};
	int expected_result{494};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence(input));
}


TEST(LengthOfLongestPalindromicSubsequenceBottomUp, short1)
{
	std::string input{"bbac"};
	int expected_result{2};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence_bottom_up(input));
}

TEST(LengthOfLongestPalindromicSubsequenceBottomUp, short2)
{
	std::string input{"abbac"};
	int expected_result{4};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence_bottom_up(input));
}

TEST(LengthOfLongestPalindromicSubsequenceBottomUp, long1)
{
	std::string input
		{"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"};
	int expected_result{494};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence_bottom_up(input));
}


TEST(LengthOfLongestPalindromicSubsequenceBottomUpLessMemory, short1)
{
	std::string input{"bbac"};
	int expected_result{2};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence_bottom_up_less_memory(input));
}

TEST(LengthOfLongestPalindromicSubsequenceBottomUpLessMemory, short2)
{
	std::string input{"abbac"};
	int expected_result{4};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence_bottom_up_less_memory(input));
}

TEST(LengthOfLongestPalindromicSubsequenceBottomUpLessMemory, long1)
{
	std::string input
		{"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"};
	int expected_result{494};
	EXPECT_EQ(expected_result, length_of_longest_palindromic_subsequence_bottom_up_less_memory(input));
}
