//
// Created by andreas on 10.12.22.
//

#ifndef MAXIMUM_DIFFERENCE_BETWEE_NODE_AND_ANCESTOR_H
#define MAXIMUM_DIFFERENCE_BETWEE_NODE_AND_ANCESTOR_H

#endif //MAXIMUM_DIFFERENCE_BETWEE_NODE_AND_ANCESTOR_H
